[build]
  command = "npm run build || echo 'No build command'"
  publish = "."

[dev]
  command = "npm run dev"
  port = 8888
  framework = "#static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "0" # Deaktiviert Go-Installation

[context.production]
  command = "npm run build || echo 'No build command'"

[context.preview]
  command = "npm run build || echo 'No build command'"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://app.netlify.com"
    Content-Security-Policy = "frame-ancestors 'self' https://app.netlify.com https://*.netlify.app;" 